module.exports = {
	/**
	 * Action Constanrs
	 */
	LOAD_TICKET_TYPES: "LOAD_TICKET_TYPES",
	LOAD_TICKET_TYPES_SUCCESS: "LOAD_TICKET_TYPES_SUCCESS",
	LOAD_TICKET_TYPES_FAILURE: "LOAD_TICKET_TYPES_FAILURE",

	CHANGE_TICKET_QUANTITY: "CHANGE_TICKET_QUANTITY",
	SAVE_TICKET_FORM_DATA: "SAVE_TICKET_FORM_DATA",
	ASSIGN_SEAT_TO_TICKET: "ASSIGN_SEAT_TO_TICKET",
	LOAD_MAKE_RESERVATION: "LOAD_MAKE_RESERVATION",
	LOAD_MAKE_RESERVATION_SUCCESS: "LOAD_MAKE_RESERVATION_SUCCESS",
	LOAD_MAKE_RESERVATION_FAILURE: "LOAD_MAKE_RESERVATION_FAILURE",
	ALL_SEATS_UNRESERVED: "ALL_SEATS_UNRESERVED",
	CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
	CHECKOUT_ERROR: "CHECKOUT_ERROR",
	INIT_CHECKOUT: "INIT_CHECKOUT",
	CHECKOUT_LOADING: "CHECKOUT_LOADING",

	LOAD_ROOMS: "LOAD_ROOMS",
	LOAD_ROOMS_SUCCESS: "LOAD_ROOMS_SUCCESS",
	LOAD_ROOMS_FAILURE: "LOAD_ROOMS_FAILURE",
	LOAD_SEATS: "LOAD_SEATS",
	LOAD_SEATS_SUCCESS: "LOAD_SEATS_SUCCESS",
	LOAD_SEATS_FAILURE: "LOAD_SEATS_FAILURE",

	LOAD_SEAT_STATUSES: "LOAD_SEAT_STATUSES",
	LOAD_SEAT_STATUSES_SUCCESS: "LOAD_SEAT_STATUSES_SUCCESS",
	LOAD_SEAT_STATUSES_FAILURE: "LOAD_SEAT_STATUSES_FAILURE",
	SEAT_STATUS_CHANGED: "SEAT_STATUS_CHANGED",

	/**
	 * Misc Constants
	 */
	EVENT_ID: 1,
	RESERVATION_API: "/reservations"
};