module.exports = {
	/**
	 * Action Constanrs
	 */
	LOAD_TICKET_TYPES: "LOAD_TICKET_TYPES",
	LOAD_TICKET_TYPES_SUCCESS: "LOAD_TICKET_TYPES_SUCCESS",
	LOAD_TICKET_TYPES_FAILURE: "LOAD_TICKET_TYPES_FAILURE",

	CHANGE_TICKET_QUANTITY: "CHANGE_TICKET_QUANTITY",
	SAVE_TICKET_FORM_DATA: "SAVE_TICKET_FORM_DATA",
	ASSIGN_SEAT_TO_TICKET: "ASSIGN_SEAT_TO_TICKET",
	LOAD_MAKE_RESERVATION: "LOAD_MAKE_RESERVATION",
	LOAD_MAKE_RESERVATION_SUCCESS: "LOAD_MAKE_RESERVATION_SUCCESS",
	LOAD_MAKE_RESERVATION_FAILURE: "LOAD_MAKE_RESERVATION_FAILURE",
	ALL_SEATS_UNRESERVED: "ALL_SEATS_UNRESERVED",
	CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
	CHECKOUT_ERROR: "CHECKOUT_ERROR",
	INIT_CHECKOUT: "INIT_CHECKOUT",
	CHECKOUT_LOADING: "CHECKOUT_LOADING",
	SET_ADMIN_GUEST_CHECKOUT: "SET_ADMIN_GUEST_CHECKOUT",
	RESET_CHECKOUT: "RESET_CHECKOUT",

	LOAD_ROOMS: "LOAD_ROOMS",
	LOAD_ROOMS_SUCCESS: "LOAD_ROOMS_SUCCESS",
	LOAD_ROOMS_FAILURE: "LOAD_ROOMS_FAILURE",
	LOAD_SEATS: "LOAD_SEATS",
	LOAD_SEATS_SUCCESS: "LOAD_SEATS_SUCCESS",
	LOAD_SEATS_FAILURE: "LOAD_SEATS_FAILURE",

	LOAD_SEAT_STATUSES: "LOAD_SEAT_STATUSES",
	LOAD_SEAT_STATUSES_SUCCESS: "LOAD_SEAT_STATUSES_SUCCESS",
	LOAD_SEAT_STATUSES_FAILURE: "LOAD_SEAT_STATUSES_FAILURE",
	SEAT_STATUS_CHANGED: "SEAT_STATUS_CHANGED",

	LOGIN_LOADING: "LOGIN_LOADING",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_ERROR: "LOGIN_ERROR",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	SESSION_CHECK_LOADING: "SESSION_CHECK_LOADING",
	SESSION_CHECK_SUCCESS: "SESSION_CHECK_SUCCESS",
	SESSION_CHECK_ERROR: "SESSION_CHECK_ERROR",
	USER_PROFILE_LOADING: "USER_PROFILE_LOADING",
	USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
	USER_PROFILE_ERROR: "USER_PROFILE_ERROR",
	UPDATE_PROFILE_LOADING: "UPDATE_PROFILE_LOADING",
	UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
	UPDATE_PROFILE_ERROR: "UPDATE_PROFILE_ERROR",
	UPDATE_EMAIL_LOADING: "UPDATE_EMAIL_LOADING",
	UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
	UPDATE_EMAIL_ERROR: "UPDATE_EMAIL_ERROR",
	UPDATE_PASSWORD_LOADING: "UPDATE_PASSWORD_LOADING",
	UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
	UPDATE_PASSWORD_ERROR: "UPDATE_PASSWORD_ERROR",
	REGISTER_LOADING: "REGISTER_LOADING",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_ERROR: "REGISTER_ERROR",

	ADMIN_ORDERS_LOADING: "ADMIN_ORDERS_LOADING",
	ADMIN_ORDERS_SUCCESS: "ADMIN_ORDERS_SUCCESS",
	ADMIN_ORDERS_ERROR: "ADMIN_ORDERS_ERROR",
	ADMIN_ORDER_DETAIL_LOADING: "ADMIN_ORDER_DETAIL_LOADING",
	ADMIN_ORDER_DETAIL_SUCCESS: "ADMIN_ORDER_DETAIL_SUCCESS",
	ADMIN_ORDER_DETAIL_ERROR: "ADMIN_ORDER_DETAIL_ERROR",
	ADMIN_CHECK_IN_ID_LOADING: "ADMIN_CHECK_IN_ID_LOADING",
	ADMIN_CHECK_IN_ID_SUCCESS: "ADMIN_CHECK_IN_ID_SUCCESS",
	ADMIN_CHECK_IN_ID_ERROR: "ADMIN_ORDER_DETAIL_ERROR",

	CHECK_IN_HASH_LOADING: "CHECK_IN_HASH_LOADING",
	CHECK_IN_HASH_SUCCESS: "CHECK_IN_HASH_SUCCESS",
	CHECK_IN_HASH_ERROR: "CHECK_IN_HASH_ERROR",
	CHECK_IN_DISMISS: "CHECK_IN_DISMISS",

	/**
	 * Misc Constants
	 */
	EVENT_ID: 1,
	RESERVATION_API: "/reservations"
};